// GANGA BAVANI Fashion & Fancy - Product Database
const PRODUCTS_DATA = [
  // --- SAREES ---
  {
    id: 1,
    name: "Pure Kanjivaram Bridal Silk Saree (Crimson Red & Gold Zari)",
    category: "sarees",
    subcategory: "Kanjivaram Silk",
    price: 14999,
    originalPrice: 19999,
    rating: 4.9,
    reviewCount: 148,
    image: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80",
    badge: "Pure Silk Mark",
    fabric: "100% Pure Mulberry Silk with 2G Gold Zari",
    occasion: "Wedding",
    blouse: "Unstitched Contrast Brocade Blouse (0.8m)",
    sizes: ["Standard (6.3m with blouse)"],
    colors: ["#8B0000", "#D4AF37", "#4A0E17"],
    description: "Masterpiece handwoven Kanchipuram bridal silk saree with traditional peacock and temple border motifs. Handcrafted by master weavers with government-certified Silk Mark guarantee."
  },
  {
    id: 2,
    name: "Royal Banarasi Katan Silk Saree in Peacock Blue",
    category: "sarees",
    subcategory: "Banarasi Silk",
    price: 9499,
    originalPrice: 12999,
    rating: 4.8,
    reviewCount: 92,
    image: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80",
    badge: "Bestseller",
    fabric: "Fine Katan Silk with Kadwa Weave",
    occasion: "Festive",
    blouse: "Running Silk Blouse with Zari border",
    sizes: ["Standard (6.3m with blouse)"],
    colors: ["#004953", "#C5A059", "#002366"],
    description: "Intricately handwoven Banarasi saree featuring regal jaal floral work in antique gold zari. Perfect for festive celebrations and luxury wedding guest wear."
  },
  {
    id: 3,
    name: "Pastel Lavender Chanderi Tissue Organza Saree",
    category: "sarees",
    subcategory: "Organza & Tissue",
    price: 4899,
    originalPrice: 6999,
    rating: 4.7,
    reviewCount: 64,
    image: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80",
    badge: "Trending",
    fabric: "Lightweight Chanderi Silk Tissue",
    occasion: "Party",
    blouse: "Designer Embroidered Blouse Fabric",
    sizes: ["Standard (6.3m with blouse)"],
    colors: ["#E6E6FA", "#D8BFD8", "#F5F5F5"],
    description: "Graceful and feather-light pastel organza saree with delicate scalloped cutwork border and shimmer finish. Ideal for modern daytime receptions and sangeet parties."
  },
  {
    id: 4,
    name: "Traditional Gadwal Pattu Saree in Mustard & Magenta",
    category: "sarees",
    subcategory: "Gadwal Silk",
    price: 8299,
    originalPrice: 10500,
    rating: 4.8,
    reviewCount: 53,
    image: "https://images.unsplash.com/photo-1610030469668-932d0f367683?auto=format&fit=crop&w=800&q=80",
    badge: "Handloom",
    fabric: "Pure Gadwal Silk Cotton Body with Silk Zari Border",
    occasion: "Festive",
    blouse: "Contrast Magenta Zari Blouse",
    sizes: ["Standard (6.3m with blouse)"],
    colors: ["#FFDB58", "#CA1F7B", "#800020"],
    description: "Classic South Indian Gadwal saree featuring lightweight cotton body interlocked with rich pure silk zari kuttu borders. High comfort with royal appeal."
  },
  {
    id: 5,
    name: "Daily Comfort Mulmul Cotton Saree (Hand Block Printed)",
    category: "sarees",
    subcategory: "Cotton Sarees",
    price: 1699,
    originalPrice: 2499,
    rating: 4.6,
    reviewCount: 110,
    image: "https://images.unsplash.com/photo-1609357605129-26f69add5d6e?auto=format&fit=crop&w=800&q=80",
    badge: "Daily Wear",
    fabric: "100% Breathable Malmal Cotton",
    occasion: "Daily Wear",
    blouse: "Matching Hand-block Print Blouse",
    sizes: ["Standard (6.2m with blouse)"],
    colors: ["#2E8B57", "#FFF8DC", "#8B4513"],
    description: "Super soft, breathable pure Mulmul cotton saree with natural dye Bagru floral prints. Soft on skin and stays fresh throughout long working hours."
  },
  {
    id: 6,
    name: "Mysore Crepe Silk Saree with Antique Gold Border",
    category: "sarees",
    subcategory: "Crepe Silk",
    price: 6499,
    originalPrice: 8999,
    rating: 4.9,
    reviewCount: 78,
    image: "https://images.unsplash.com/photo-1610030470298-0570b201f11a?auto=format&fit=crop&w=800&q=80",
    badge: "Pure Silk",
    fabric: "Pure Mysore Crepe Silk with Gold Zari Pallu",
    occasion: "Wedding",
    blouse: "Running Silk Blouse with Zari lace",
    sizes: ["Standard (6.3m with blouse)"],
    colors: ["#800020", "#B22222", "#4B0082"],
    description: "Rich drape, flawless fall, and royal sheen. Pure Mysore Crepe silk crafted for weddings, temple visits, and family celebrations."
  },

  // --- WOMEN'S WEAR ---
  {
    id: 7,
    name: "Royal Heritage Bridal Lehenga in Crimson Velvet",
    category: "women",
    subcategory: "Bridal Lehengas",
    price: 21999,
    originalPrice: 29999,
    rating: 5.0,
    reviewCount: 67,
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=800&q=80",
    badge: "Bridal Special",
    fabric: "Micro Velvet with Zardozi & Dori Embroidery",
    occasion: "Wedding",
    sizes: ["Semi-Stitched (Fits 32 to 44)"],
    colors: ["#800020", "#D4AF37"],
    description: "Magnificent bridal lehenga choli ensemble loaded with heritage zardozi, sequin, and dori embroidery. Comes with double dupatta set (velvet + sheer net)."
  },
  {
    id: 8,
    name: "Anarkali Kurta Set with Banarasi Silk Dupatta",
    category: "women",
    subcategory: "Anarkali Sets",
    price: 3899,
    originalPrice: 5499,
    rating: 4.7,
    reviewCount: 89,
    image: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80",
    badge: "Festive Pick",
    fabric: "Chanderi Silk Kurta with Cotton Lining",
    occasion: "Festive",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["#00563B", "#C5A059", "#1E4D2B"],
    description: "Floor-length royal green flared Anarkali paired with matching pants and a heavy Banarasi silk zari woven dupatta. Ideal for Diwali, Eid, and family functions."
  },
  {
    id: 9,
    name: "Embroidered Straight Kurti with Palazzo Pant",
    category: "women",
    subcategory: "Kurtis & Suits",
    price: 1899,
    originalPrice: 2799,
    rating: 4.5,
    reviewCount: 142,
    image: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80",
    badge: "Top Seller",
    fabric: "Pure Rayon Viscose with Thread Work",
    occasion: "Daily Wear",
    sizes: ["M", "L", "XL", "XXL", "3XL"],
    colors: ["#4B0082", "#9932CC", "#FFB6C1"],
    description: "Comfortable and stylish daily wear straight cut kurti with intricate Lucknowi style chikankari chest embroidery, paired with soft palazzo trousers."
  },
  {
    id: 10,
    name: "Designer Floral Georgette Gown with Belt",
    category: "women",
    subcategory: "Gowns",
    price: 2999,
    originalPrice: 4200,
    rating: 4.6,
    reviewCount: 45,
    image: "https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=800&q=80",
    badge: "Party Wear",
    fabric: "Flowy Fox Georgette with Digital Print",
    occasion: "Party",
    sizes: ["S", "M", "L", "XL"],
    colors: ["#FF69B4", "#483D8B", "#FFD700"],
    description: "Stunning full-flare evening gown featuring modern digital floral prints, can-can inner support, and an embellished mirror-work metallic belt."
  },

  // --- MEN'S WEAR ---
  {
    id: 11,
    name: "Imperial Groom Sherwani Set with Stole & Churidar",
    category: "men",
    subcategory: "Sherwanis",
    price: 12999,
    originalPrice: 17999,
    rating: 4.9,
    reviewCount: 52,
    image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80",
    badge: "Wedding Masterpiece",
    fabric: "Raw Silk with Hand Embroidered Zari & Sequins",
    occasion: "Wedding",
    sizes: ["38 (M)", "40 (L)", "42 (XL)", "44 (XXL)"],
    colors: ["#FFFDD0", "#D4AF37", "#800020"],
    description: "Regal ivory sherwani with intricately hand-embroidered floral motifs, antique metal buttons, matching royal maroon embroidered stole, and silk churidar."
  },
  {
    id: 12,
    name: "Pure Silk Dhoti with Gold Zari Angavastram (Pattu Pancha)",
    category: "men",
    subcategory: "Traditional Dhotis",
    price: 3499,
    originalPrice: 4999,
    rating: 4.9,
    reviewCount: 88,
    image: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=800&q=80",
    badge: "Traditional South",
    fabric: "100% Pure Silk with Mayilkan Border",
    occasion: "Wedding",
    sizes: ["9x5 Dhoti + Angavastram"],
    colors: ["#FFFFF0", "#C5A059"],
    description: "Authentic South Indian wedding Pattu Pancha dhoti set with rich 3-inch temple zari border. Blessed comfort for poojas, festivals, and traditional wedding ceremonies."
  },
  {
    id: 13,
    name: "Raw Silk Kurta Pajama with Brocade Nehru Jacket",
    category: "men",
    subcategory: "Kurta Sets",
    price: 4299,
    originalPrice: 5999,
    rating: 4.8,
    reviewCount: 71,
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80",
    badge: "Festive Hit",
    fabric: "Art Silk Kurta with Banarasi Brocade Modi Jacket",
    occasion: "Festive",
    sizes: ["38", "40", "42", "44"],
    colors: ["#002366", "#D4AF37", "#F0F8FF"],
    description: "Royal Navy blue straight kurta paired with white churidar and an opulent gold floral woven Banarasi Nehru / Modi jacket."
  },
  {
    id: 14,
    name: "Classic Linen Formal & Festive Men's Shirt",
    category: "men",
    subcategory: "Shirts",
    price: 1599,
    originalPrice: 2299,
    rating: 4.6,
    reviewCount: 60,
    image: "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=800&q=80",
    badge: "All-Day Classic",
    fabric: "100% Pure Breathable European Linen",
    occasion: "Daily Wear",
    sizes: ["39 (S)", "40 (M)", "42 (L)", "44 (XL)"],
    colors: ["#FFFFFF", "#E0FFFF", "#FFE4E1"],
    description: "Premium pure linen long sleeve shirt. Unmatched breathability, crisp tailoring, and comfortable fit for festive gatherings and executive wear."
  },

  // --- KIDS' WEAR ---
  {
    id: 15,
    name: "Girls Traditional Pattu Pavadai (Silk Lehenga Set)",
    category: "kids",
    subcategory: "Girls Ethnic",
    price: 2499,
    originalPrice: 3499,
    rating: 4.9,
    reviewCount: 95,
    image: "https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?auto=format&fit=crop&w=800&q=80",
    badge: "Little Princess",
    fabric: "Kanchi Silk Brocade with Soft Cotton Inner Lining",
    occasion: "Wedding",
    sizes: ["1-2 Yrs", "2-4 Yrs", "4-6 Yrs", "6-8 Yrs", "8-10 Yrs"],
    colors: ["#FF1493", "#FFD700", "#008080"],
    description: "Handcrafted South Indian Pattu Pavadai for young girls. Soft, itch-free cotton inner lining with gleaming gold zari peacocks and contrast pleated skirt."
  },
  {
    id: 16,
    name: "Boys Royal Dhoti Kurta Set with Angavastram",
    category: "kids",
    subcategory: "Boys Ethnic",
    price: 1999,
    originalPrice: 2899,
    rating: 4.8,
    reviewCount: 64,
    image: "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=800&q=80",
    badge: "Traditional Cutie",
    fabric: "Silk Blend Kurta with Ready-to-Wear Elastic Dhoti",
    occasion: "Festive",
    sizes: ["1-2 Yrs", "2-4 Yrs", "4-6 Yrs", "6-8 Yrs", "8-10 Yrs"],
    colors: ["#FFD700", "#800020", "#FFF8DC"],
    description: "Traditional ready-made dhoti-kurta set tailored for young boys. Elasticated waist for instant, hassle-free dress-up during poojas and weddings."
  },
  {
    id: 17,
    name: "Girls Sparkle Festive Party Gown with Tiara",
    category: "kids",
    subcategory: "Girls Western",
    price: 2199,
    originalPrice: 3200,
    rating: 4.7,
    reviewCount: 42,
    image: "https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=800&q=80",
    badge: "Party Wear",
    fabric: "Net & Satin with Sequin Bodice & Butterfly Bow",
    occasion: "Party",
    sizes: ["2-3 Yrs", "4-5 Yrs", "6-7 Yrs", "8-9 Yrs"],
    colors: ["#FFC0CB", "#E6E6FA", "#87CEEB"],
    description: "Dreamy fairytale birthday and celebration ball gown with multiple layers of soft tulle net, glitter sequin bodice, and complimentary princess hairband."
  },
  {
    id: 18,
    name: "Boys Indo-Western Sherwani Style Kurta Set",
    category: "kids",
    subcategory: "Boys Ethnic",
    price: 2399,
    originalPrice: 3399,
    rating: 4.8,
    reviewCount: 39,
    image: "https://images.unsplash.com/photo-1503919545889-aef636e10ad4?auto=format&fit=crop&w=800&q=80",
    badge: "Festive Hit",
    fabric: "Jacquard Silk with Comfortable Cotton Lining",
    occasion: "Wedding",
    sizes: ["2-4 Yrs", "4-6 Yrs", "6-8 Yrs", "8-10 Yrs", "10-12 Yrs"],
    colors: ["#4169E1", "#C5A059", "#FFFFFF"],
    description: "Dapper asymmetric overlap Indo-Western jacket kurta with pocket square and stretchable churidar pants for young boys."
  },

  // --- FANCY & ACCESSORIES ---
  {
    id: 19,
    name: "Antique Temple Jewellery Choker Set with Jhumkas",
    category: "fancy",
    subcategory: "Temple Jewellery",
    price: 2899,
    originalPrice: 4500,
    rating: 4.9,
    reviewCount: 112,
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80",
    badge: "Bridal Antique",
    fabric: "Gold Plated Brass with Kemp Stones & Pearls",
    occasion: "Wedding",
    sizes: ["Adjustable Dori Choker + Hanging Earrings"],
    colors: ["#D4AF37", "#800020", "#006400"],
    description: "Handcrafted South Indian temple jewellery set with Goddess Lakshmi motifs, high-grade ruby kemp stones, and cascading fresh-water pearl drops."
  },
  {
    id: 20,
    name: "Bridal Silk Thread Glass Bangle Set (Box of 24)",
    category: "fancy",
    subcategory: "Bangles & Chuda",
    price: 1199,
    originalPrice: 1799,
    rating: 4.8,
    reviewCount: 86,
    image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&q=80",
    badge: "Handmade Fancy",
    fabric: "Raw Silk Thread Wrapped with Kundan Stones & Pearls",
    occasion: "Festive",
    sizes: ["2.4 (Small)", "2.6 (Medium)", "2.8 (Large)"],
    colors: ["#FF0000", "#FFD700", "#008000"],
    description: "Exquisite handmade silk thread bangle box with rich kundan flower cutwork and pearl latkans. Perfectly color-coordinated for bridal and festival lehengas."
  },
  {
    id: 21,
    name: "Handcrafted Zardozi Pearl Potli Bag",
    category: "fancy",
    subcategory: "Bags & Clutches",
    price: 1499,
    originalPrice: 2199,
    rating: 4.7,
    reviewCount: 75,
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80",
    badge: "Accessory Star",
    fabric: "Pure Raw Silk with Pearl Tassel Drawstrings",
    occasion: "Wedding",
    sizes: ["Standard (8 x 9 inches)"],
    colors: ["#D4AF37", "#800020", "#FFFFFF"],
    description: "Luxurious handcrafted wedding potli bag with intricate pearl beadwork, gold zardozi embroidery, and ornate beaded shoulder cord."
  },
  {
    id: 22,
    name: "Banarasi Pure Katan Silk Dupatta with Zari Jaal",
    category: "fancy",
    subcategory: "Dupattas & Shawls",
    price: 2499,
    originalPrice: 3699,
    rating: 4.9,
    reviewCount: 58,
    image: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80",
    badge: "Silk Heritage",
    fabric: "100% Katan Silk with Antique Zari Weave",
    occasion: "Festive",
    sizes: ["Full Length (2.5 meters x 36 inches)"],
    colors: ["#B22222", "#D4AF37", "#004953"],
    description: "Rich statement Banarasi silk dupatta designed to elevate any plain kurti or lehenga into a festive couture statement."
  },
  {
    id: 23,
    name: "Kundan & Meenakari Maang Tikka with Passa Hair Ornament",
    category: "fancy",
    subcategory: "Hair Jewellery",
    price: 999,
    originalPrice: 1599,
    rating: 4.6,
    reviewCount: 47,
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80",
    badge: "Bridal Glow",
    fabric: "Brass with Meenakari Enameling & Uncut Kundan",
    occasion: "Wedding",
    sizes: ["One Size Fits All"],
    colors: ["#D4AF37", "#FFFFFF", "#800020"],
    description: "Traditional royal Rajasthani Kundan forehead ornament (Maang Tikka) with hand-painted meenakari detailing and delicate pearl strings."
  },
  {
    id: 24,
    name: "Soft Banarasi Organza Floral Saree in Sage Green",
    category: "sarees",
    subcategory: "Organza & Tissue",
    price: 5299,
    originalPrice: 7499,
    rating: 4.8,
    reviewCount: 51,
    image: "https://images.unsplash.com/photo-1610030469668-932d0f367683?auto=format&fit=crop&w=800&q=80",
    badge: "New Arrival",
    fabric: "Pure Organza Silk with Silver & Gold Zari Booti",
    occasion: "Party",
    blouse: "Embroidered Silk Blouse Piece",
    sizes: ["Standard (6.3m with blouse)"],
    colors: ["#9CAF88", "#C5A059", "#FFFFFF"],
    description: "Subtle and sophisticated sage green organza saree adorned with delicate silver-gold dual zari floral motifs and soft borders."
  }
];

// Department / Category Meta Configuration
const CATEGORIES_META = [
  { id: "all", name: "All Collections", icon: "fa-sparkles", count: 24 },
  { id: "sarees", name: "Sarees & Pattu", icon: "fa-ring", count: 7 },
  { id: "women", name: "Women's Ethnic", icon: "fa-vest-patches", count: 4 },
  { id: "men", name: "Men's Wear", icon: "fa-user-tie", count: 4 },
  { id: "kids", name: "Kids' Collection", icon: "fa-child", count: 4 },
  { id: "fancy", name: "Fancy & Jewellery", icon: "fa-gem", count: 5 }
];
